name: github repository secret scanning
on: [ push, pull_request ]
jobs:
  ref-check:
    runs-on: ubuntu-22.04
    outputs:
      push: ${{ steps.push.outputs.ref }}
      pr: ${{ steps.pr.outputs.ref }}
    steps:
    - name: output ref(push)
      if: github.event_name != 'pull_request'
      id: push
      run: |
        echo "::set-output name=ref::${{ github.ref }}"
    - name: output ref(pr)
      if: github.event_name == 'pull_request'
      id: pr
      run: |
        echo "::set-output name=ref::${{ github.head_ref }}"

  secret-scanning:
    needs: [ ref-check ]
    runs-on: ubuntu-22.04
    steps:
    - name: choose ref
      id: event
      run: |
        push=${{ needs.ref-check.outputs.push }}
        pr=${{ needs.ref-check.outputs.pr }}
        if [[ $push =~ refs/heads ]]; then
          echo "::set-output name=ref::$(echo $push)"
        else
          echo "::set-output name=ref::$(echo $pr)"
        fi
    - name: repo scanning
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        ref: ${{ steps.event.outputs.ref }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: install trufflehog3
      run: |
        pip install trufflehog3
    - name: scanning secrets
      run: |
        trufflehog3 -z -r rules.yml --branch ${{ steps.event.outputs.ref }} --no-entropy
    - name: create report.json
      run: |
        trufflehog3 -z -r rules.yml --branch ${{ steps.event.outputs.ref }} --no-entropy --format json --output report.json
        trufflehog3 -R ${GITHUB_WORKSPACE}/report.json --output scan-report.html
    - name: upload report
      uses: actions/upload-artifact@v3
      with:
        name: secret-scanning-artifact
        path: scan-report.html
