name: github repository secret scanning 1
on: [ push, pull_request ]
jobs:
  secret-scanning:
    runs-on: ubuntu-22.04
    steps:
    - name: check ref
      run: |
        ${{ github.ref }}
        ${{ github.head_ref }}

    # - name: basic repo
    #   uses: actions/checkout@v3
    #   with:
    #       fetch-depth: 2
    #       ref: ${{ github.ref }}
    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.8'
    # - name: install trufflehog3
    #   run: |
    #     pip install trufflehog3
    # - name: scanning secrets
    #   run: |
    #     trufflehog3 -z -r rules.yml --branch ${{ github.ref }} --no-entropy
    # - name: create report.json
    #   run: |
    #     trufflehog3 -z -r rules.yml --branch ${{ github.ref }} --no-entropy --format json --output report.json
    #     trufflehog3 -R ${GITHUB_WORKSPACE}/report.json --output report.html
    # - name: upload report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: secret-scan-artifact
    #     path: report.html
